defaults: &defaults
  errbit:
    api_key: <%= ENV['HDR_ERRBIT_KEY'] %>
    host: <%= ENV['HDR_ERRBIT_HOST'] %>
    port: <%= ENV['HDR_ERRBIT_PORT'] %>
  log:
    level: "info"
  estimate:
    path: <%= File.join(Grape::ROOT, "public") %>

development:
  <<: *defaults
  log:
    level: "debug"

test:
  <<: *defaults
  log:
    level: "warn"

production: &production
  <<: *defaults
  estimate:
    path: "/repos/data-retriever/"


staging:
  <<: *production
  estimate:
    path: "/repos/data-retriever/"
